/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Feedback
import org.openapitools.client.models.FeedbackType

class FeedbackTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Feedback
        //val modelInstance = Feedback()

        // to test the property `sessionId` - The session ID this feedback should be attached to.
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

        // to test the property `type` - The type of feedback.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `score` - The score of the feedback.
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `comment` - The comment of the feedback.
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `groupId` - The message group ID this feedback should be attached to.
        should("test groupId") {
            // uncomment below to test the property
            //modelInstance.groupId shouldBe ("TODO")
        }

    }
}
