/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ModelInfoOutput
import org.openapitools.client.models.OptionalToolSet

class ModelInfoOutputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModelInfoOutput
        //val modelInstance = ModelInfoOutput()

        // to test the property `modelString` - The string used to identify the model.
        should("test modelString") {
            // uncomment below to test the property
            //modelInstance.modelString shouldBe ("TODO")
        }

        // to test the property `version` - The version of the model.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `isExperimental` - Whether the model is experimental or not.
        should("test isExperimental") {
            // uncomment below to test the property
            //modelInstance.isExperimental shouldBe ("TODO")
        }

        // to test the property `toolsets` - Toggable tools used by the model.
        should("test toolsets") {
            // uncomment below to test the property
            //modelInstance.toolsets shouldBe ("TODO")
        }

    }
}
