/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OpResult
import org.openapitools.client.models.MimeType
import org.openapitools.client.models.ResponseStatus

class OpResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OpResult
        //val modelInstance = OpResult()

        // to test the property `ok` - True if the operation was successful.
        should("test ok") {
            // uncomment below to test the property
            //modelInstance.ok shouldBe ("TODO")
        }

        // to test the property `statusCode` - HTTP status code to return.
        should("test statusCode") {
            // uncomment below to test the property
            //modelInstance.statusCode shouldBe ("TODO")
        }

        // to test the property `statusMessage` - Describe why the operation failed.
        should("test statusMessage") {
            // uncomment below to test the property
            //modelInstance.statusMessage shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `mimeType`
        should("test mimeType") {
            // uncomment below to test the property
            //modelInstance.mimeType shouldBe ("TODO")
        }

        // to test the property `latency`
        should("test latency") {
            // uncomment below to test the property
            //modelInstance.latency shouldBe ("TODO")
        }

    }
}
