/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OptionalToolSet
import org.openapitools.client.models.ToolSetVendor

class OptionalToolSetTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OptionalToolSet
        //val modelInstance = OptionalToolSet()

        // to test the property `name` - The name of the toolset.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `version` - The version of the toolset.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `vendor` - The vendor of the toolset.
        should("test vendor") {
            // uncomment below to test the property
            //modelInstance.vendor shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `isEnabled` - Whether the toolset is enabled or not.
        should("test isEnabled") {
            // uncomment below to test the property
            //modelInstance.isEnabled shouldBe ("TODO")
        }

        // to test the property `isExperimental` - Whether the toolset is experimental or not.
        should("test isExperimental") {
            // uncomment below to test the property
            //modelInstance.isExperimental shouldBe ("TODO")
        }

    }
}
