/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PublicUser
import org.openapitools.client.models.PublicUserVendor
import org.openapitools.client.models.UserType

class PublicUserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicUser
        //val modelInstance = PublicUser()

        // to test the property `id` - The user ID this session belongs to.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `orgId` - The organization ID this session belongs to.
        should("test orgId") {
            // uncomment below to test the property
            //modelInstance.orgId shouldBe ("TODO")
        }

        // to test the property `type` - The type of user.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `neverLog` - The user session should never be logged.
        should("test neverLog") {
            // uncomment below to test the property
            //modelInstance.neverLog shouldBe ("TODO")
        }

        // to test the property `canDisableLogging` - Is user authorized to disable logging.
        should("test canDisableLogging") {
            // uncomment below to test the property
            //modelInstance.canDisableLogging shouldBe ("TODO")
        }

        // to test the property `keyExpireTime` - The Unix timestamp (in seconds) of when the key will expire.
        should("test keyExpireTime") {
            // uncomment below to test the property
            //modelInstance.keyExpireTime shouldBe ("TODO")
        }

        // to test the property `tpm` - Tokens per minute quota.
        should("test tpm") {
            // uncomment below to test the property
            //modelInstance.tpm shouldBe ("TODO")
        }

        // to test the property `rpm` - Requests per minute quota.
        should("test rpm") {
            // uncomment below to test the property
            //modelInstance.rpm shouldBe ("TODO")
        }

        // to test the property `allowExperimental` - Whether the user is allowed to use experimental features.
        should("test allowExperimental") {
            // uncomment below to test the property
            //modelInstance.allowExperimental shouldBe ("TODO")
        }

        // to test the property `vendors` - The list of vendors the user has access to.
        should("test vendors") {
            // uncomment below to test the property
            //modelInstance.vendors shouldBe ("TODO")
        }

    }
}
