/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SessionResponse
import org.openapitools.client.models.Message
import org.openapitools.client.models.Usage

class SessionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionResponse
        //val modelInstance = SessionResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `messages`
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

        // to test the property `statusCode` - The status code of the message. 2xx is Okay, 4xx is a client error, 5xx is a server error.
        should("test statusCode") {
            // uncomment below to test the property
            //modelInstance.statusCode shouldBe ("TODO")
        }

        // to test the property `statusMessage` - Explain status code reason.
        should("test statusMessage") {
            // uncomment below to test the property
            //modelInstance.statusMessage shouldBe ("TODO")
        }

        // to test the property `usage` - Usage statistics for the message.
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

    }
}
