/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ToolSetVendor

class ToolSetVendorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ToolSetVendor
        //val modelInstance = ToolSetVendor()

        // to test the property `name` - The name of the vendor providing the tool or agent.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - A brief description of the vendor.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `url` - The URL of vendor.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `svg` - The SVG icon of the vendor.
        should("test svg") {
            // uncomment below to test the property
            //modelInstance.svg shouldBe ("TODO")
        }

    }
}
