/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Usage

class UsageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Usage
        //val modelInstance = Usage()

        // to test the property `promptTokens` - Number of tokens in the prompt
        should("test promptTokens") {
            // uncomment below to test the property
            //modelInstance.promptTokens shouldBe ("TODO")
        }

        // to test the property `generatedTokens` - Number of tokens used during generation
        should("test generatedTokens") {
            // uncomment below to test the property
            //modelInstance.generatedTokens shouldBe ("TODO")
        }

        // to test the property `totalTokens` - Total number of tokens used in the request (prompt + generation)
        should("test totalTokens") {
            // uncomment below to test the property
            //modelInstance.totalTokens shouldBe ("TODO")
        }

    }
}
