/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UserInfo
import org.openapitools.client.models.ModelInfoOutput
import org.openapitools.client.models.PublicSessionOutput
import org.openapitools.client.models.PublicUser

class UserInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserInfo
        //val modelInstance = UserInfo()

        // to test the property `user` - The user information.
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `sessions` - The list of users active sessions.
        should("test sessions") {
            // uncomment below to test the property
            //modelInstance.sessions shouldBe ("TODO")
        }

        // to test the property `availableModels` - The list of models available to the user.
        should("test availableModels") {
            // uncomment below to test the property
            //modelInstance.availableModels shouldBe ("TODO")
        }

    }
}
