/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.Attachment
import org.openapitools.client.models.ChatCompletionRequest
import org.openapitools.client.models.ChatCompletionResponse
import org.openapitools.client.models.Feedback
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.OpResult
import org.openapitools.client.models.PublicSessionInput
import org.openapitools.client.models.PublicSessionOutput
import org.openapitools.client.models.SessionRequest
import org.openapitools.client.models.SessionResponse
import org.openapitools.client.models.UserInfo

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test attachV1SessionAttachFilePost
        should("test attachV1SessionAttachFilePost") {
            // uncomment below to test attachV1SessionAttachFilePost
            //val attachment : Attachment =  // Attachment | 
            //val result : OpResult = apiInstance.attachV1SessionAttachFilePost(attachment)
            //result shouldBe ("TODO")
        }

        // to test completeChatCompletionsPost
        should("test completeChatCompletionsPost") {
            // uncomment below to test completeChatCompletionsPost
            //val chatCompletionRequest : ChatCompletionRequest =  // ChatCompletionRequest | 
            //val result : ChatCompletionResponse = apiInstance.completeChatCompletionsPost(chatCompletionRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteFileV1SessionDeleteFilePost
        should("test deleteFileV1SessionDeleteFilePost") {
            // uncomment below to test deleteFileV1SessionDeleteFilePost
            //val attachment : Attachment =  // Attachment | 
            //val result : OpResult = apiInstance.deleteFileV1SessionDeleteFilePost(attachment)
            //result shouldBe ("TODO")
        }

        // to test deleteV1SessionDeletePost
        should("test deleteV1SessionDeletePost") {
            // uncomment below to test deleteV1SessionDeletePost
            //val publicSessionInput : PublicSessionInput =  // PublicSessionInput | 
            //val result : OpResult = apiInstance.deleteV1SessionDeletePost(publicSessionInput)
            //result shouldBe ("TODO")
        }

        // to test diagnosticsV1SystemDiagnosticGet
        should("test diagnosticsV1SystemDiagnosticGet") {
            // uncomment below to test diagnosticsV1SystemDiagnosticGet
            //val result : kotlin.Any = apiInstance.diagnosticsV1SystemDiagnosticGet()
            //result shouldBe ("TODO")
        }

        // to test feedbackV1SessionFeedbackPost
        should("test feedbackV1SessionFeedbackPost") {
            // uncomment below to test feedbackV1SessionFeedbackPost
            //val feedback : Feedback =  // Feedback | 
            //val result : OpResult = apiInstance.feedbackV1SessionFeedbackPost(feedback)
            //result shouldBe ("TODO")
        }

        // to test generateV1SessionGeneratePost
        should("test generateV1SessionGeneratePost") {
            // uncomment below to test generateV1SessionGeneratePost
            //val sessionRequest : SessionRequest =  // SessionRequest | 
            //val result : SessionResponse = apiInstance.generateV1SessionGeneratePost(sessionRequest)
            //result shouldBe ("TODO")
        }

        // to test getAgentGraphV1SystemAgentGraphGet
        should("test getAgentGraphV1SystemAgentGraphGet") {
            // uncomment below to test getAgentGraphV1SystemAgentGraphGet
            //val result : kotlin.Any = apiInstance.getAgentGraphV1SystemAgentGraphGet()
            //result shouldBe ("TODO")
        }

        // to test getAgentV1SystemAgentGet
        should("test getAgentV1SystemAgentGet") {
            // uncomment below to test getAgentV1SystemAgentGet
            //val height : kotlin.Int = 56 // kotlin.Int | 
            //val experimental : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.Any = apiInstance.getAgentV1SystemAgentGet(height, experimental)
            //result shouldBe ("TODO")
        }

        // to test getGet
        should("test getGet") {
            // uncomment below to test getGet
            //val result : kotlin.Any = apiInstance.getGet()
            //result shouldBe ("TODO")
        }

        // to test getV1SessionGetGet
        should("test getV1SessionGetGet") {
            // uncomment below to test getV1SessionGetGet
            //val sessionId : kotlin.String = sessionId_example // kotlin.String | 
            //val result : PublicSessionOutput = apiInstance.getV1SessionGetGet(sessionId)
            //result shouldBe ("TODO")
        }

        // to test healthCheckHealthGet
        should("test healthCheckHealthGet") {
            // uncomment below to test healthCheckHealthGet
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.healthCheckHealthGet()
            //result shouldBe ("TODO")
        }

        // to test infoV1UserInfoGet
        should("test infoV1UserInfoGet") {
            // uncomment below to test infoV1UserInfoGet
            //val result : UserInfo = apiInstance.infoV1UserInfoGet()
            //result shouldBe ("TODO")
        }

        // to test listV1SessionListGet
        should("test listV1SessionListGet") {
            // uncomment below to test listV1SessionListGet
            //val result : kotlin.collections.List<PublicSessionOutput> = apiInstance.listV1SessionListGet()
            //result shouldBe ("TODO")
        }

        // to test registerV1SessionRegisterPost
        should("test registerV1SessionRegisterPost") {
            // uncomment below to test registerV1SessionRegisterPost
            //val publicSessionInput : PublicSessionInput =  // PublicSessionInput | 
            //val result : OpResult = apiInstance.registerV1SessionRegisterPost(publicSessionInput)
            //result shouldBe ("TODO")
        }

        // to test tsMockV1ExperimentalTsGet
        should("test tsMockV1ExperimentalTsGet") {
            // uncomment below to test tsMockV1ExperimentalTsGet
            //val result : kotlin.Any = apiInstance.tsMockV1ExperimentalTsGet()
            //result shouldBe ("TODO")
        }

        // to test updateV1SessionUpdatePost
        should("test updateV1SessionUpdatePost") {
            // uncomment below to test updateV1SessionUpdatePost
            //val publicSessionInput : PublicSessionInput =  // PublicSessionInput | 
            //val result : OpResult = apiInstance.updateV1SessionUpdatePost(publicSessionInput)
            //result shouldBe ("TODO")
        }

    }
}
