/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MimeType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a file upload to the session.
 *
 * @param sessionId The session ID this file should be attached to.
 * @param filename The name of the file.
 * @param mimeType The mime type of the file.
 * @param content The content of the file as string. Always base64 encoded.
 */


data class Attachment (

    /* The session ID this file should be attached to. */
    @Json(name = "session_id")
    val sessionId: kotlin.String,

    /* The name of the file. */
    @Json(name = "filename")
    val filename: kotlin.String,

    /* The mime type of the file. */
    @Json(name = "mime_type")
    val mimeType: MimeType,

    /* The content of the file as string. Always base64 encoded. */
    @Json(name = "content")
    val content: kotlin.String

) {


}

