/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OpenAIMessage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param model 
 * @param messages 
 * @param temperature 
 * @param topP 
 * @param n 
 * @param stream 
 * @param maxTokens 
 * @param presencePenalty 
 * @param frequencyPenalty 
 * @param user 
 * @param metadata 
 */


data class ChatCompletionRequest (

    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "messages")
    val messages: kotlin.collections.List<OpenAIMessage>,

    @Json(name = "temperature")
    val temperature: java.math.BigDecimal? = null,

    @Json(name = "top_p")
    val topP: java.math.BigDecimal? = null,

    @Json(name = "n")
    val n: kotlin.Int? = null,

    @Json(name = "stream")
    val stream: kotlin.Boolean? = null,

    @Json(name = "max_tokens")
    val maxTokens: kotlin.Int? = null,

    @Json(name = "presence_penalty")
    val presencePenalty: java.math.BigDecimal? = null,

    @Json(name = "frequency_penalty")
    val frequencyPenalty: java.math.BigDecimal? = null,

    @Json(name = "user")
    val user: kotlin.String? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

