/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OpenAIMessage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param index 
 * @param message 
 * @param finishReason 
 */


data class Choice (

    @Json(name = "index")
    val index: kotlin.Int,

    @Json(name = "message")
    val message: OpenAIMessage,

    @Json(name = "finish_reason")
    val finishReason: kotlin.String

) {


}

