/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FeedbackType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a feedback to the session.
 *
 * @param sessionId The session ID this feedback should be attached to.
 * @param type The type of feedback.
 * @param score The score of the feedback.
 * @param comment The comment of the feedback.
 * @param groupId The message group ID this feedback should be attached to.
 */


data class Feedback (

    /* The session ID this feedback should be attached to. */
    @Json(name = "session_id")
    val sessionId: kotlin.String,

    /* The type of feedback. */
    @Json(name = "type")
    val type: FeedbackType,

    /* The score of the feedback. */
    @Json(name = "score")
    val score: kotlin.Int,

    /* The comment of the feedback. */
    @Json(name = "comment")
    val comment: kotlin.String,

    /* The message group ID this feedback should be attached to. */
    @Json(name = "group_id")
    val groupId: kotlin.String? = ""

) {


}

