/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Type of message
 *
 * Values: result,source,debug,info,error,thinking,update,delete,confirmation_request,confirmation_response,query
 */

@JsonClass(generateAdapter = false)
enum class MessageType(val value: kotlin.String) {

    @Json(name = "result")
    result("result"),

    @Json(name = "source")
    source("source"),

    @Json(name = "debug")
    debug("debug"),

    @Json(name = "info")
    info("info"),

    @Json(name = "error")
    error("error"),

    @Json(name = "thinking")
    thinking("thinking"),

    @Json(name = "update")
    update("update"),

    @Json(name = "delete")
    delete("delete"),

    @Json(name = "confirmation_request")
    confirmation_request("confirmation_request"),

    @Json(name = "confirmation_response")
    confirmation_response("confirmation_response"),

    @Json(name = "query")
    query("query");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MessageType) "$data" else null

        /**
         * Returns a valid [MessageType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MessageType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

