/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OptionalToolSet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Describes a Sec-Gemini model.
 *
 * @param modelString The string used to identify the model.
 * @param version The version of the model.
 * @param isExperimental Whether the model is experimental or not.
 * @param toolsets Toggable tools used by the model.
 */


data class ModelInfoInput (

    /* The string used to identify the model. */
    @Json(name = "model_string")
    val modelString: kotlin.String,

    /* The version of the model. */
    @Json(name = "version")
    val version: kotlin.String,

    /* Whether the model is experimental or not. */
    @Json(name = "is_experimental")
    val isExperimental: kotlin.Boolean? = false,

    /* Toggable tools used by the model. */
    @Json(name = "toolsets")
    val toolsets: kotlin.collections.List<OptionalToolSet>? = null

) {


}

