/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Content

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param content 
 */


data class OpenAIMessage (

    @Json(name = "role")
    val role: OpenAIMessage.Role,

    @Json(name = "content")
    val content: Content

) {

    /**
     * 
     *
     * Values: system,user,assistant
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "system") system("system"),
        @Json(name = "user") user("user"),
        @Json(name = "assistant") assistant("assistant");
    }

}

