/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MimeType
import org.openapitools.client.models.ResponseStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ok True if the operation was successful.
 * @param statusCode HTTP status code to return.
 * @param statusMessage Describe why the operation failed.
 * @param `data` 
 * @param mimeType 
 * @param latency 
 */


data class OpResult (

    /* True if the operation was successful. */
    @Json(name = "ok")
    val ok: kotlin.Boolean,

    /* HTTP status code to return. */
    @Json(name = "status_code")
    val statusCode: ResponseStatus,

    /* Describe why the operation failed. */
    @Json(name = "status_message")
    val statusMessage: kotlin.String? = "",

    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "mime_type")
    val mimeType: MimeType? = null,

    @Json(name = "latency")
    val latency: java.math.BigDecimal? = null

) {


}

