/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ToolSetVendor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Describes the toolsets of a Sec-Gemini model.
 *
 * @param name The name of the toolset.
 * @param version The version of the toolset.
 * @param vendor The vendor of the toolset.
 * @param description 
 * @param isEnabled Whether the toolset is enabled or not.
 * @param isExperimental Whether the toolset is experimental or not.
 */


data class OptionalToolSet (

    /* The name of the toolset. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The version of the toolset. */
    @Json(name = "version")
    val version: kotlin.Int,

    /* The vendor of the toolset. */
    @Json(name = "vendor")
    val vendor: ToolSetVendor,

    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Whether the toolset is enabled or not. */
    @Json(name = "is_enabled")
    val isEnabled: kotlin.Boolean? = true,

    /* Whether the toolset is experimental or not. */
    @Json(name = "is_experimental")
    val isExperimental: kotlin.Boolean? = false

) {


}

