/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Only add the fields necessary to show to users.
 *
 * @param name The original name of the file.
 * @param mimeType The mime type of the file.
 */


data class PublicSessionFile (

    /* The original name of the file. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The mime type of the file. */
    @Json(name = "mime_type")
    val mimeType: kotlin.String

) {


}

