/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Message
import org.openapitools.client.models.Usage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param messages 
 * @param statusCode The status code of the message. 2xx is Okay, 4xx is a client error, 5xx is a server error.
 * @param statusMessage Explain status code reason.
 * @param usage Usage statistics for the message.
 */


data class SessionResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "messages")
    val messages: kotlin.collections.List<Message>,

    /* The status code of the message. 2xx is Okay, 4xx is a client error, 5xx is a server error. */
    @Json(name = "status_code")
    val statusCode: kotlin.Int,

    /* Explain status code reason. */
    @Json(name = "status_message")
    val statusMessage: kotlin.String,

    /* Usage statistics for the message. */
    @Json(name = "usage")
    val usage: Usage

) {


}

