/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Message

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Schema for the request body for triggering a model generation.
 *
 * @param messages new query messages
 * @param id The Session ID (UUID4) this request belongs to.
 */


data class SessionRequest (

    /* new query messages */
    @Json(name = "messages")
    val messages: kotlin.collections.List<Message>,

    /* The Session ID (UUID4) this request belongs to. */
    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

