/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Vendor Toolsets info.
 *
 * @param name The name of the vendor providing the tool or agent.
 * @param description A brief description of the vendor.
 * @param url The URL of vendor.
 * @param svg The SVG icon of the vendor.
 */


data class ToolSetVendor (

    /* The name of the vendor providing the tool or agent. */
    @Json(name = "name")
    val name: kotlin.String,

    /* A brief description of the vendor. */
    @Json(name = "description")
    val description: kotlin.String,

    /* The URL of vendor. */
    @Json(name = "url")
    val url: kotlin.String,

    /* The SVG icon of the vendor. */
    @Json(name = "svg")
    val svg: kotlin.String

) {


}

