/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Tracks token usage for a chat completion request and response.
 *
 * @param promptTokens Number of tokens in the prompt
 * @param generatedTokens Number of tokens used during generation
 * @param totalTokens Total number of tokens used in the request (prompt + generation)
 */


data class Usage (

    /* Number of tokens in the prompt */
    @Json(name = "prompt_tokens")
    val promptTokens: kotlin.Int? = 0,

    /* Number of tokens used during generation */
    @Json(name = "generated_tokens")
    val generatedTokens: kotlin.Int? = 0,

    /* Total number of tokens used in the request (prompt + generation) */
    @Json(name = "total_tokens")
    val totalTokens: kotlin.Int? = 0

) {


}

