/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ModelInfoOutput
import org.openapitools.client.models.PublicSessionOutput
import org.openapitools.client.models.PublicUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param user The user information.
 * @param sessions The list of users active sessions.
 * @param availableModels The list of models available to the user.
 */


data class UserInfo (

    /* The user information. */
    @Json(name = "user")
    val user: PublicUser,

    /* The list of users active sessions. */
    @Json(name = "sessions")
    val sessions: kotlin.collections.List<PublicSessionOutput>? = null,

    /* The list of models available to the user. */
    @Json(name = "available_models")
    val availableModels: kotlin.collections.List<ModelInfoOutput>? = null

) {


}

