/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * User type
 *
 * Values: ui,user,admin,system,service
 */

@JsonClass(generateAdapter = false)
enum class UserType(val value: kotlin.String) {

    @Json(name = "ui")
    ui("ui"),

    @Json(name = "user")
    user("user"),

    @Json(name = "admin")
    admin("admin"),

    @Json(name = "system")
    system("system"),

    @Json(name = "service")
    service("service");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UserType) "$data" else null

        /**
         * Returns a valid [UserType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UserType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

